### ISSUE TITLE
Resetting the selection doesn't work

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#13]
When a word/phrase is selected, and I click outside (on a non-selected word, or on the background), then the menu for the selected word/phrase should be reset.

Assume the sentence "fienden besegrar Afrika". If I click "Afrika" twice, "besegrar Afrika" is selected. Now, if I click "fienden" only that word will be selected, but if I click "Afrika" again then the whole sentence is selected. I.e., the selection doesn't reset.

**Comment by heatherleaf** [comment]
Sorry, not completely solved yet. Here are some click sequences that give strange results (I use "Exemplum Pars"):

1. click "fienden", then "besegrar", then "fienden": the whole sentence is selected
2. click "besegrar", then "Afrika", then "besegrar": the phrase "besegrar Afrika" is selected
3. both remain even if you click the background after the second click (i.e., "fienden" + "besegrar" + background + "fienden")

**Comment by fredefox** [comment]
Ah! I know what the problem is here! Note to self:

The problem is that `show_lin` calls

https://github.com/MUSTE-Project/MULLE/blob/1aa492130f8cf157902dcc1427035639d986b799/muste-ajax/static/muste-gui.js#L296-L299

and so does not `clear_selection`, but it must do this if the word we're clicking has changed.
