### ISSUE TITLE
Questions about depth-limit

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#44]
Two questions about the depth-limit options. No implementation to be done (yet), first I have to understand things.

1. Are `--limit-prune` and `--limit-adjunctions` really different from each other? The reason I ask is because in `Options.hs` they have the same `O.metavar`:

          pruneSearchDepthParser
            = optional
            $ O.option O.auto
              (  O.long "limit-prune"
              <> O.help "Limit search depth when creating pruning trees"
              <> O.metavar "DEPTH"
              )
    
          searchDepthParser
            = optional
            $ O.option O.auto
              (  O.long "limit-adjunctions"
              <> O.help "Limit search depth when creating adjunction trees"
              <> O.metavar "DEPTH"
              )

    Also, in `AdjunctionTrees.hs` you have `BuilderInfo {searchDepth ∷ Maybe Int}`, and in `Prune.hs` you have `PruneOpts {searchDepth ∷ Maybe Int}`. Both use the same name `searchDepth` -- but on the other hand, it's not the same as the `O.metavar` name ("DEPTH"). There's something here I don't understand.

    I don't think they have to be different -- both kinds of pruning can use the same variable. But then we don't need two options. 

2. Now you're using these options to limit search/pruning **depth**, but I think I would prefer to limit the **size** of the pruned tree. Would it be possible to change to pruning by size instead? (Without adding too much complexity)

    With size I mean the number of function nodes in a tree. I.e., `Tree.Internal.countNodes` (but of course the limit check should not call `countNodes` -- that would be inefficient)

**Comment by heatherleaf** [comment]
2b. Perhaps it's possible to have both pruning by depth and size? Two options to the cli (assuming the same option to pruning and adjunction trees)

**Comment by heatherleaf** [comment]
Thanks for the info!

Just being curious: How can two different variables have the same name (`searchDepth`)? And where in the code does that variable get its value? There is something in the options parser I don't understand...

**Comment by fredefox** [comment]
I had to thread a lot of needles to get it from the front-end (the CLI options) to where it was needed. This is also why I've been trying to make the code use a more monadic style.

In Haskell2010 you can have record fields that have the same name by placing them in seperate modules. This is sufficient in this case. With `-XDuplicateRecordFields` they can occur in the same module. This is nice because you don't have to arbitrarily prefix your record fields.

Perhaps these commits can help you understand what's going on:

* Pruner was made monadic: 0be01282fa9a177e226d50ca823a48011320032b
* Here I put more of the environment into the monad: 4496d7e62b4221a429fe4bc569dcb97f71ab998f notice how we can make e.g. `replaceTreesM` go from having 3 arguments to having none!
* Here I actually hook up the new monad with the new option: 63f2338d518f4b6562fda9fe11d872ac8ae9ea14 - notice here how little needs to be changed!

And for the full effect:

https://github.com/MUSTE-Project/MULLE/compare/e21fb7c798d05ecafdcb112720d19be9978388bb...63f2338d518f4b6562fda9fe11d872ac8ae9ea14

**Comment by heatherleaf** [comment]
Ha! Finally I see how it works... stupid me, I didn't read lines 19-29 and 42-52 in Options.hs correctly...

**Comment by fredefox** [comment]
And the Great Lambda said unto the people: "Let no person call themselves stupid that they understand Haskell!"

**Comment by heatherleaf** [comment]
Closing this, continuing in issue #46
