### ISSUE TITLE
GUI: Show completed exercise

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#78]
When I finish an exercise, the solution is not shown at all, but it just hurries on to the next exercise, without any notice.

I want:
1. the final sentence(s) to update, and then
2. a modal window to display with a message that the exercise is complete, with the score X, and two buttons: 
   - (a) continue to next exercise, or (b) go back to lessons view
   - if it's the final exercise, the window should say that the lesson is completed, and then only offer the option to go back to the lessons view

**Comment by fredefox** [comment]
This should be fairly easy.

**Comment by fredefox** [comment]
This is done in 8e7e184. I think that should cover all there is. As always, if I missed something; reopen.

**Comment by heatherleaf** [comment]
Still some (hopefully minor) problems:

1. I select Eng-Swe, and solve all 4 lessons
2. when I'm finished with the last one (which is "övning 3 av 4" according to issue #79), it says "Exercise complete, continue lesson?". If I click "ok" it stays on the last exercise
3. when I cancel the exercise ("Avbryt lektion"), it says "4 avklarade av 4 övningar"
4. if I select "Eng->Swe" again, nothing happens: it sends a post to the server but gets a 400 response ("bad request")

Even more strange:

5. if I log out and login again, the "Eng->Swe" lesson disappears completely
6. if I log out and login as another user, the "Eng->Swe" lesson is still lost

**Comment by fredefox** [comment]
When I try to do it, the following happens:

* I solve the first 3 exercise. Everything goes as expected.
* When I solve the 4th and final exercise it incorrectly says, exercise complete, continue lesson?
* I click yes, and it stays on the exercise.
* When I go back to the lessons view I do still see the lesson, but I cannot select it. I get the "no unsolved exercises" error (which I was aware of). Remind me again what we want to have happen here.

**Comment by fredefox** [comment]
The exercise does indeed disappear if I log in again. I suspect this may be becuase the "finishedness" is (incorrectly) hooked up to the session since this is the only thing that should change in this case.

**Comment by fredefox** [comment]
I think I've found the issue:

https://github.com/MUSTE-Project/MULLE/blob/04212a62e719a5fbf97d8a6667e582395570e7a9/muste-ajax/src/Muste/Web/Database.hs#L805-L819

The key to the exercise is unique. So surely this should always return 0 or 1. I think the fix is to swap the key from referring to an exercise to referring to a lesson.

**Comment by fredefox** [comment]
So I've gone ahead and increased the type-safety of the Database module even further in 139846e. Two issues has appeared after doing this:

* `getUser` returns the id of the session, not the user! Surely this is a mistake.
* `getFinishedExercises` same issue as described above.

**Comment by fredefox** [comment]
So I've fixed some of these issues. The increased type safety is really a big boon. There are still some issue with the database. These are likely regressions introduced by myself during my changes that touched the database. I mentioned this to @daherb so he should be aware that there are some issues here.

An issue remains that the amount of finished exercises (as displayed on the lesson list) is incorrect. If you try to solve it, it will still tell you that you've solved the lesson. The reason the number is reported incorrectly is because of an issue with the following sql view:

https://github.com/MUSTE-Project/MULLE/blob/802a4e4068ea27d2bb734c95a5d1ff1acc1a774c/muste-ajax/data/sql/create.sql#L152-L181

The problem arose because I was a bit confused by the data model used here: "How does `FinishedExercise`, `StartedLesson`, `FinishedLesson`, and `ExerciseList` play together?"

If I don't manage to fix all regressions I might've introduced here I'm sure Herbert will be able to do it afterwards. But please be more liberal with foreign keys and joins! Having redundancy across and moving data from one table to another can be really confusing.

So yeah. A wall of text here... I'll try investigating more and see if I can fix the remaining issues.

**Comment by fredefox** [comment]
Still thinking about this. I don't remember exactly what we want to have happen when a lesson is completed. Currently it adds a new batch of exercises to the to-be-solved list. So when it says e.g. 4 of 2 finished exercises it is not strictly wrong...

**Comment by heatherleaf** [comment]
Here's how it works now for me. I start with `--recreate-db`, log in as "peter" and solve the lesson "Two lessons" (should perhaps be called "two exercises":): 

![image](https://user-images.githubusercontent.com/1324196/47498507-c09ef080-d85d-11e8-9173-330f2b790ad7.png)

I log out and log in again as "peter", and the lesson is still there. 

Then I log out and log in as "herbert", and the lesson disappears:

![image](https://user-images.githubusercontent.com/1324196/47498550-d8767480-d85d-11e8-9ef3-f5b04bff810f.png)

I log out and log in as "peter", and the lesson is back (magic!)

Now I select the (finished) lesson, and solve it (replace "book" with "Paris"), and get a javascript error:

![image](https://user-images.githubusercontent.com/1324196/47498688-47ec6400-d85e-11e8-90e0-ec9202fc5ada.png)

**Comment by fredefox** [comment]
There are two things at play here:

  - [ ] Active lessons for a given user is handled incorrectly
  - [ ] Trying to solve exercises in a solved lesson is not allowed. We need to figure out how we want to handle this.

**Comment by fredefox** [comment]
The problem with the first bullet is the usage of `LEFT JOIN` here:

https://github.com/MUSTE-Project/MULLE/blob/5438c3bddbe0feb8c0963e64d920260bfe2224fc/muste-ajax/data/sql/create.sql#L163

If there is an entry in the exercise list for the given exercise then it will pair it up with the user that solved it. However, it will not include a row for that exercise where there is not user.

**Comment by fredefox** [comment]
Found a hack [here](http://www.sqlitetutorial.net/sqlite-full-outer-join/) it's super awkward though.

**Comment by fredefox** [comment]
We should've used a no-sql database!

**Comment by fredefox** [comment]
I've solved the problem related with the view in a5756a4. Other problems persist.

**Comment by fredefox** [comment]
I've entirely disallowed starting a finished lesson in 556ad10 until we figure out how to handle this properly.

**Comment by heatherleaf** [comment]
I notice that I get a Javascript error when I try to select an already-solved lesson. Perhaps it would be more helpful with an alert window? (Or greying out the button)

**Comment by fredefox** [comment]
Yes we should do that. Can we create a separate issue?
